# Root
baseURL = 'https://arcade.aao.fyi/'
languageCode = 'en'
theme = 'codeberg.org/aao-fyi/shock'

# Info
title = 'Arcade'
copyright = 'aao.fyi'

# Features
disableHugoGeneratorInject = false
disableKinds = ['taxonomy','term']
enableGitInfo = true
enableRobotsTXT = true

# Timeout
timeout = '90s'

# Minify
[minify]
  minifyOutput = true

# Build
[build]
  # PostCSS
  writeStats = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.146.0'
  # Logo
  [[module.imports]]
    path = 'gitlab.com/aao-fyi/gitlab-profile'
  [[module.imports.mounts]]
    source = 'logos/arcade/'
    target = 'assets/img/logo/'

  # Skyrim
  [[module.imports]]
    path = 'codeberg.org/aao-fyi/arcade-skyrim'
  # Desolate Point
  [[module.imports.mounts]]
    source = 'desolate-point/README.md'
    target = 'assets/skyrim/desolate-point/README.md'
  # Fort Resource
  [[module.imports.mounts]]
    source = 'fort-resource/README.md'
    target = 'assets/skyrim/fort-resource/README.md'
  # Rider Tombs
  [[module.imports.mounts]]
    source = 'rider-tombs/README.md'
    target = 'assets/skyrim/rider-tombs/README.md'
  # Skeever Tail Shack
  [[module.imports.mounts]]
    source = 'skeever-tail-shack/README.md'
    target = 'assets/skyrim/skeever-tail-shack/README.md'
  # Horker Tusk Homestead
  [[module.imports.mounts]]
    source = 'horker-tusk-homestead/README.md'
    target = 'assets/skyrim/horker-tusk-homestead/README.md'
  # Vault 106
  [[module.imports.mounts]]
    source = 'vault-106/README.md'
    target = 'assets/skyrim/vault-106/README.md'

  # Kerbal Space Program
  [[module.imports]]
    path = 'codeberg.org/aao-fyi/arcade-ksp'
  # Fawkes
  [[module.imports.mounts]]
    source = 'fawkes/README.md'
    target = 'assets/ksp/fawkes/README.md'
  # GalaNet
  [[module.imports.mounts]]
    source = 'galanet/README.md'
    target = 'assets/ksp/galanet/README.md'
  # SpaceEgg
  [[module.imports.mounts]]
    source = 'spaceegg/README.md'
    target = 'assets/ksp/spaceegg/README.md'

  # Team Fortress 2
  # Nav Fortress
  [[module.imports]]
    path = 'codeberg.org/aao-fyi/arcade-tf2'
  [[module.imports.mounts]]
    source = 'nav-fortress/README.md'
    target = 'assets/tf2/nav-fortress/README.md'

[menu]
  # Connect
  [[menu.connect]]
    identifier = 'nexus'
    name = 'Nexus'
    weight = '15'
    color = '#d98f40'
    url = 'https://nexusmods.com/profile/aaofyi/'
    [menu.connect.params]
      icon = 'shrink'
  [[menu.connect]]
    identifier = 'kerbalx'
    name = 'KerbalX'
    weight = '50'
    color = '#2c5999'
    url = 'https://kerbalx.com/aao-fyi/'
  [menu.connect.params]
      icon = 'square-x'
  # Footer
  [[menu.footer]]
    identifier = 'sitemap'
    name = 'Sitemap'
    weight = '89'
    url = '/sitemap.xml'
  [[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy'
    weight = '90'
    url = 'https://aao.fyi/privacy/'
  [[menu.footer]]
    identifier = 'terms'
    name = 'Terms'
    weight = '91'
    url = 'https://aao.fyi/terms/'
