# Root
baseURL = 'https://arcade.aao.fyi/'
languageCode = 'en'
theme = 'gitlab.com/aao-fyi/shock'

# Info
title = 'Arcade'
copyright = 'aao.fyi'

# Features
disableHugoGeneratorInject = false
disableKinds = ['RSS','taxonomy','term']
enableGitInfo = true
enableRobotsTXT = true

# Minify
[minify]
  minifyOutput = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.111.0'

# Footer
[menu]
  [[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy'
    url = 'https://aao.fyi/privacy/'
  [[menu.footer]]
    identifier = 'sitemap'
    name = 'Sitemap'
    url = '/sitemap.xml'
